export type Word = { english: string; meaning: string; example: string; exampleKo: string; known: boolean; saved: boolean };
const w = (english: string, meaning: string, example: string, exampleKo: string): Word => ({english,meaning,example,exampleKo,known:false,saved:false});
export const wordKey = (value: string) => value.toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g," ").trim();
export const starterWords: Word[] = [
  w("commute", "통근하다; 출퇴근", "My commute takes about an hour, so I listen to English on the train.", "출근에 한 시간 정도 걸려서 전철에서 영어를 들어요."),
  w("run late", "예정보다 늦어지다", "I'm running a little late because the train was delayed.", "전철이 지연되어 조금 늦고 있어요."),
  w("be in charge of", "~을 담당하다", "I'm in charge of checking the delivery schedule.", "저는 배송 일정을 확인하는 일을 담당해요."),
  w("handle", "처리하다; 담당하다", "I handle customer requests and coordinate with the sales team.", "고객 요청을 처리하고 영업팀과 업무를 조율해요."),
  w("coordinate", "조율하다", "Could you coordinate the meeting time with the team?", "팀과 회의 시간을 조율해 주시겠어요?"),
  w("available", "시간이 되는; 이용 가능한", "Are you available for a quick call this afternoon?", "오늘 오후에 잠깐 통화할 시간 되세요?"),
  w("reschedule", "일정을 변경하다", "Could we reschedule our meeting for Thursday morning?", "회의를 목요일 오전으로 변경할 수 있을까요?"),
  w("push back", "일정을 뒤로 미루다", "Can we push the meeting back by thirty minutes?", "회의를 30분 미룰 수 있을까요?"),
  w("follow up on", "~의 진행 상황을 다시 확인하다", "I'm following up on the email I sent yesterday.", "어제 보낸 이메일에 대해 다시 확인드려요."),
  w("get back to", "~에게 다시 연락하다", "I'll check with my manager and get back to you by noon.", "매니저에게 확인하고 정오까지 다시 연락드릴게요."),
  w("clarify", "명확히 설명하다", "Could you clarify what you mean by the final version?", "최종본이 무엇을 뜻하는지 명확히 설명해 주시겠어요?"),
  w("confirm", "확인하다; 확정하다", "Could you confirm the delivery date before we place the order?", "주문 전에 배송일을 확인해 주시겠어요?"),
  w("deadline", "마감 기한", "The deadline is Friday, but I need one more day to review it.", "마감은 금요일인데 검토할 시간이 하루 더 필요해요."),
  w("due", "마감인; 예정된", "The report is due tomorrow, so I'm working on the final section.", "보고서 마감이 내일이라 마지막 부분을 작업하고 있어요."),
  w("on track", "계획대로 진행 중인", "We're on track to finish the project by the end of the week.", "이번 주 말까지 프로젝트를 마칠 수 있도록 계획대로 진행 중이에요."),
  w("behind schedule", "예정보다 늦어진", "We're slightly behind schedule because we're waiting for approval.", "승인을 기다리고 있어서 일정이 조금 늦어졌어요."),
  w("priority", "우선순위; 우선할 일", "My first priority today is to resolve the delivery issue.", "오늘 가장 먼저 할 일은 배송 문제를 해결하는 거예요."),
  w("update", "최신 소식; 진행 상황을 알리다", "Do you have any updates on the order we placed last week?", "지난주에 넣은 주문에 대해 새로 나온 소식이 있나요?"),
  w("issue", "문제; 사안", "We've found an issue with the invoice and need to check it.", "청구서에서 문제를 발견해서 확인이 필요해요."),
  w("resolve", "문제를 해결하다", "We're working with the supplier to resolve the issue.", "문제를 해결하기 위해 공급업체와 협의 중이에요."),
  w("shipment", "배송 물품; 발송", "The shipment has been delayed, but it should arrive tomorrow.", "배송이 지연됐지만 내일은 도착할 예정이에요."),
  w("supplier", "공급업체", "I'll contact the supplier to check whether the items are in stock.", "상품이 재고에 있는지 공급업체에 연락해 확인할게요."),
  w("in stock", "재고가 있는", "Is this model still in stock, or do we need to wait?", "이 모델은 아직 재고가 있나요, 아니면 기다려야 하나요?"),
  w("estimate", "예상하다; 예상치", "Could you give me an estimate of how long the repair will take?", "수리에 얼마나 걸릴지 예상 시간을 알려주시겠어요?"),
  w("double-check", "한 번 더 확인하다", "Let me double-check the numbers before I send the report.", "보고서를 보내기 전에 수치를 한 번 더 확인할게요."),
  w("make sure", "반드시 ~하도록 하다; 확인하다", "Please make sure everyone has the updated file.", "모두가 수정된 파일을 갖고 있는지 확인해 주세요."),
  w("in the meantime", "그동안; 그 사이에", "The manager is reviewing it. In the meantime, I'll prepare the slides.", "매니저가 검토 중이에요. 그동안 저는 발표 자료를 준비할게요."),
  w("work for you", "시간·방법이 괜찮다", "Would Thursday at three work for you?", "목요일 3시는 괜찮으세요?"),
  w("bring up", "화제를 꺼내다", "I'd like to bring up one more point before we finish.", "마치기 전에 한 가지 더 말씀드리고 싶어요."),
  w("wrap up", "마무리하다", "Let's wrap up by confirming who's responsible for each task.", "각 업무의 담당자를 확인하면서 마무리해요."),
];
