import type { Lesson, Phrase } from "./lessons";

// IDs 11–20 preserve the completed records of the original 1–10 course.
const p = (en: string, ko: string, cue: string, cueKo: string, task: string, tip: string, from: string, to: string, change: string): Phrase => ({en, ko, cue, cueKo, task, tip, variation:{from,to,task:change}});

export const workLessons: Lesson[] = [
{id:11,title:"출근길 이야기로 대화 이어가기",label:"일상 · 이유와 되묻기",scene:"동료와 짧은 대화를 나눕니다. 답에 이유나 세부 내용을 붙이고, 상대에게도 질문해보세요.",phrases:[
p("My train was delayed, so I got here a little late. How was your commute?","전철이 지연돼서 조금 늦게 도착했어요. 출근길은 어땠어요?","How was your morning?","오늘 아침은 어땠어요?","전철이 지연돼 늦었다고 설명하고, 상대의 출근길도 물어보세요.","so로 이유와 결과를 연결한 뒤, 질문을 붙이면 대화가 이어져요.","train","bus","전철 대신 버스가 지연된 상황으로 바꿔 말하세요."),
p("I usually take the subway because it's faster. It takes about an hour.","더 빨라서 보통 지하철을 타요. 한 시간쯤 걸려요.","How do you usually get to work?","보통 어떻게 출근하세요?","지하철을 타는 이유와 걸리는 시간을 두 문장으로 설명하세요.","because 뒤에는 이유를, It takes 뒤에는 걸리는 시간을 말해요.","an hour","forty minutes","출근에 걸리는 시간을 40분으로 바꿔 설명하세요."),
p("I stayed home and watched a movie. What did you do over the weekend?","집에서 영화를 봤어요. 주말에 뭐 하셨어요?","Did you have a good weekend?","주말 잘 보내셨어요?","집에서 한 일을 말하고, 상대는 주말에 무엇을 했는지 물어보세요.","끝난 일을 말할 때 stayed, watched처럼 과거형을 써요.","watched a movie","read a book","영화를 본 대신 책을 읽었다고 말하세요."),
p("I've got a busy morning, but I'm free after lunch. Do you want to grab a coffee?","오전에는 바쁘지만 점심 후에는 시간이 있어요. 커피 한잔할래요?","Do you have time for a quick chat?","잠깐 이야기할 시간 있어요?","오전에는 바쁘다고 말하고, 점심 후 커피를 제안하세요.","but으로 상황을 전환해요. grab a coffee는 편하게 커피를 마시자는 말이에요.","after lunch","at three","시간이 되는 때를 점심 후에서 3시로 바꿔 말하세요."),
p("I'm practicing English on my way to work. I want to feel more comfortable speaking.","출근길에 영어를 연습하고 있어요. 말할 때 좀 더 편해지고 싶어요.","What are you listening to?","뭘 듣고 있어요?","출근길에 영어를 연습 중이며, 말하기가 편해지고 싶다고 설명하세요.","on my way to work는 출근하는 길에, want to 뒤에는 하고 싶은 일을 붙여요.","on my way to work","during my lunch break","영어를 연습하는 때를 출근길에서 점심시간으로 바꿔 말하세요.")
]},
{id:12,title:"내 업무와 담당 범위 설명하기",label:"직장 · 자기소개 확장",scene:"처음 만난 동료가 담당 업무를 묻습니다. 직무, 구체적인 일, 도울 수 있는 범위를 함께 말해보세요.",phrases:[
p("I work in logistics. I arrange shipments and talk to customers.","저는 물류 업무를 해요. 선적을 준비하고 고객과 소통해요.","What do you do at your company?","회사에서 어떤 일을 하세요?","물류 업무를 한다고 소개하고, 담당하는 일 두 가지를 말하세요.","직무를 한 문장으로 소개한 뒤, 실제 하는 일을 동사 두 개로 설명해보세요.","talk to customers","check shipping documents","고객과 소통하는 대신 선적 서류를 확인한다고 말하세요."),
p("I'm responsible for this account. Please contact me if you have any questions.","제가 이 거래처를 담당해요. 질문이 있으면 저에게 연락해 주세요.","Who should I contact about this order?","이 주문에 관해서는 누구에게 연락해야 하나요?","자신이 담당자라고 밝히고, 질문이 있으면 연락하라고 안내하세요.","be responsible for는 담당하다, if는 조건을 붙일 때 써요.","this account","our overseas customers","담당 범위를 이 거래처에서 해외 고객으로 바꿔 말하세요."),
p("I've worked here for three years. Before that, I worked in customer service.","여기서 3년째 일하고 있어요. 그전에는 고객 서비스 업무를 했어요.","How long have you worked here?","여기서 얼마나 오래 일하셨어요?","현재 근무 기간과 이전에 했던 일을 설명하세요.","현재까지 이어지는 기간은 I've worked ... for로, 끝난 과거 업무는 I worked로 말해요.","three years","two years","현재 회사의 근무 기간을 2년으로 바꿔 말하세요."),
p("I can help you with the documents. For payment questions, please contact our finance team.","서류는 제가 도와드릴 수 있어요. 결제 문의는 재무팀에 연락해 주세요.","Can you help me with the documents and payment?","서류와 결제를 도와주실 수 있나요?","서류는 도울 수 있지만 결제 문의는 재무팀이 담당한다고 안내하세요.","help you with 뒤에는 도움을 줄 대상을 붙여요. 범위를 나누어 설명해보세요.","payment questions","invoice questions","재무팀에 연결할 문의를 결제에서 인보이스로 바꿔 말하세요."),
p("I'm still learning the new system. Could you show me how to use this feature?","새 시스템을 아직 배우는 중이에요. 이 기능을 쓰는 방법을 보여주시겠어요?","Are you familiar with the new system?","새 시스템이 익숙하신가요?","아직 배우는 중이라고 설명하고, 특정 기능의 사용법을 부탁하세요.","still은 계속되는 상태를 말해요. show me how to 뒤에 배우고 싶은 행동을 붙여요.","use this feature","download the report","기능 사용법 대신 보고서 내려받는 방법을 부탁하세요.")
]},
{id:13,title:"일정이 겹칠 때 대안 제안하기",label:"직장 · 일정 조율",scene:"회의 시간이 다른 일정과 겹칩니다. 어려운 이유를 설명하고, 가능한 시간이나 방법을 제안해보세요.",phrases:[
p("I have another meeting at two. Could we move ours to three?","2시에 다른 회의가 있어요. 우리 회의를 3시로 옮길 수 있을까요?","Does two o'clock work for you?","2시 괜찮으세요?","2시에는 다른 회의가 있다고 말하고, 3시로 변경을 요청하세요.","Could we move ... to ...?로 일정을 다른 시간으로 옮겨달라고 부탁해요.","to three","to four","대안 시간을 3시에서 4시로 바꿔 요청하세요."),
p("Friday works better for me because I need more time to prepare. Would that be okay?","준비 시간이 더 필요해서 금요일이 더 좋아요. 괜찮으실까요?","Would you prefer Thursday or Friday?","목요일과 금요일 중 어느 날이 좋으세요?","준비 시간이 필요하므로 금요일을 선호한다고 말하고 동의를 구하세요.","works better for me로 선호를 부드럽게 말하고 because로 이유를 덧붙여요.","Friday","Thursday","선호하는 날을 금요일에서 목요일로 바꿔 말하세요."),
p("I'm available between ten and eleven. We could have a quick call then.","10시부터 11시 사이에 시간이 있어요. 그때 짧게 통화해도 되겠어요.","When are you free tomorrow?","내일 언제 시간 되세요?","가능한 시간대를 밝히고, 그 시간에 짧은 통화를 제안하세요.","between A and B로 시간 범위를 말해요. could는 가능한 대안을 부드럽게 제안해요.","between ten and eleven","between two and three","가능한 시간대를 2시부터 3시로 바꿔 말하세요."),
p("Could we keep the meeting to thirty minutes? I have a deadline this afternoon.","회의를 30분 안에 마칠 수 있을까요? 오늘 오후에 마감이 있어요.","How much time do you have?","시간이 얼마나 있으세요?","회의 시간을 30분으로 제한해달라고 부탁하고 이유를 설명하세요.","keep ... to로 시간이나 범위를 제한해요. 이유까지 말하면 부탁이 더 명확해져요.","thirty minutes","twenty minutes","회의 시간을 20분으로 줄여서 요청하세요."),
p("Just to confirm, we're meeting online at three tomorrow. I'll send you the link.","확인차 말씀드리면, 내일 3시에 온라인으로 만나는 거죠. 링크를 보내드릴게요.","So, are we all set for tomorrow?","그럼 내일 일정은 확정된 건가요?","방식과 날짜, 시간을 확인하고 회의 링크를 보내겠다고 말하세요.","Just to confirm으로 결정된 사항을 다시 확인할 수 있어요.","at three","at four","회의 시간을 4시로 바꿔 다시 확인하세요.")
]},
{id:14,title:"이메일을 다시 요청하고 확인하기",label:"직장 · 요청과 후속 조치",scene:"필요한 파일이 빠졌거나 답장이 늦어지고 있습니다. 무엇이 필요한지, 언제까지 필요한지 구체적으로 말해보세요.",phrases:[
p("I received your email, but the attachment is missing. Could you send it again?","이메일은 받았는데 첨부파일이 없어요. 다시 보내주시겠어요?","Did you get the file I sent?","제가 보낸 파일 받으셨나요?","이메일은 받았지만 첨부가 빠졌다고 설명하고 재전송을 부탁하세요.","but 뒤에 문제를 말한 다음 구체적인 요청을 붙여보세요.","the attachment is missing","I can't open the attachment","첨부가 없는 대신 첨부파일이 열리지 않는 상황으로 바꿔 말하세요."),
p("Could you send me the updated file by noon? I need it for this afternoon's meeting.","수정된 파일을 정오까지 보내주시겠어요? 오늘 오후 회의에 필요해요.","When do you need the revised file?","수정된 파일이 언제까지 필요하세요?","정오까지 수정본을 요청하고 오후 회의에 필요하다고 설명하세요.","by noon은 정오까지라는 마감이에요. at noon은 정오에라는 시점이에요.","by noon","by ten","파일을 받아야 하는 시간을 10시까지로 바꿔 말하세요."),
p("I'm following up on my email from yesterday. Have you had a chance to review the proposal?","어제 보낸 이메일에 관해 다시 연락드려요. 제안서를 검토해보셨나요?","What would you like to check?","무엇을 확인하고 싶으세요?","어제 이메일의 후속 연락이라고 밝히고 제안서 검토 여부를 물어보세요.","follow up on은 이전 건의 진행 상황을 다시 확인하는 표현이에요.","the proposal","the quotation","검토 여부를 확인할 대상을 제안서에서 견적서로 바꿔 말하세요."),
p("I've attached the revised quotation. The delivery cost is included in the total.","수정된 견적서를 첨부했어요. 배송비는 총액에 포함되어 있어요.","What has changed in the quotation?","견적서에서 무엇이 바뀌었나요?","수정 견적을 첨부했다고 말하고 총액에 배송비가 포함되어 있음을 설명하세요.","is included in으로 비용이나 항목이 어디에 포함되는지 설명해요.","delivery cost","handling fee","총액에 포함된 비용을 배송비에서 취급 수수료로 바꿔 말하세요."),
p("Thanks for the update. I'll review the details and get back to you tomorrow.","알려주셔서 감사합니다. 세부 내용을 검토한 뒤 내일 다시 연락드릴게요.","Could you let me know what you think?","검토 의견을 알려주시겠어요?","업데이트에 감사하고, 검토 후 내일 답하겠다고 말하세요.","get back to you는 답변이나 확인 결과를 가지고 다시 연락한다는 뜻이에요.","tomorrow","this afternoon","답변 시점을 내일에서 오늘 오후로 바꿔 말하세요.")
]},
{id:15,title:"전화에서 숫자와 조건 확인하기",label:"직장 · 재확인",scene:"전화에서 일부를 놓쳤습니다. 전체를 반복해달라고 하기보다, 못 들은 부분을 짚어서 확인해보세요.",phrases:[
p("The line is breaking up. Could you repeat the last part?","통화가 끊겨 들려요. 마지막 부분을 다시 말씀해 주시겠어요?","Can you hear me clearly?","제 목소리가 잘 들리세요?","통화 상태가 좋지 않다고 설명하고 마지막 부분을 다시 요청하세요.","the last part처럼 필요한 부분을 짚으면 전체를 다시 듣지 않아도 돼요.","the last part","the delivery address","마지막 부분 대신 배송지 주소를 다시 말해달라고 요청하세요."),
p("Did you say fourteen or forty? I want to make sure I have the right number.","14라고 하셨나요, 40이라고 하셨나요? 숫자를 정확히 확인하고 싶어요.","We need forty boxes for this order.","이 주문에는 상자 40개가 필요해요.","14인지 40인지 다시 묻고 정확한 수량을 확인하려는 것이라고 설명하세요.","비슷하게 들리는 숫자는 두 가지를 나란히 말하며 확인해보세요.","fourteen or forty","fifteen or fifty","15인지 50인지 확인하는 상황으로 바꿔 말하세요."),
p("Let me check that I understood correctly. You need the documents by Friday, right?","제가 제대로 이해했는지 확인할게요. 금요일까지 서류가 필요하신 거죠?","Please make sure the documents arrive before the weekend.","주말 전에 서류가 도착하도록 해주세요.","이해한 내용을 다시 확인하며 서류 마감이 금요일인지 물어보세요.","상대의 요청을 자기 말로 다시 말한 뒤 right?로 확인할 수 있어요.","by Friday","by Thursday","서류가 필요한 마감을 목요일까지로 바꿔 확인하세요."),
p("Could you email me a summary after the call? That will help me confirm the details.","통화 후 요약 내용을 이메일로 보내주시겠어요? 세부 사항을 확인하는 데 도움이 될 것 같아요.","Is there anything else you need?","더 필요한 것이 있나요?","통화 요약을 이메일로 요청하고 세부 사항 확인에 필요하다고 설명하세요.","That will help me 뒤에 요약을 받으려는 목적을 붙여보세요.","confirm the details","share the details with my team","요약을 받으려는 이유를 팀에 세부 사항을 공유하기 위해서로 바꿔 말하세요."),
p("I'm in a meeting at the moment. Can I call you back in twenty minutes?","지금 회의 중이에요. 20분 후에 다시 전화드려도 될까요?","Do you have a few minutes to talk?","잠깐 통화할 시간 있으세요?","지금 통화하기 어려운 이유와 다시 전화할 시간을 함께 말하세요.","in twenty minutes는 지금부터 20분 후예요. for twenty minutes와 구별하세요.","twenty minutes","ten minutes","다시 전화할 시간을 10분 후로 바꿔 말하세요.")
]},
{id:16,title:"주문이 달라졌을 때 설명하기",label:"일상 · 요청과 대안",scene:"카페나 식당에서 원하는 조건을 설명합니다. 주문이 잘못되었을 때도 상황을 짚고 필요한 조치를 부탁해보세요.",phrases:[
p("I ordered an iced coffee, but this one is hot. Could you change it, please?","아이스커피를 주문했는데 이건 뜨거워요. 바꿔주시겠어요?","Is everything okay with your order?","주문하신 것 괜찮으세요?","아이스로 주문했는데 뜨거운 음료를 받았다고 설명하고 교환을 요청하세요.","주문한 것과 받은 것을 but으로 비교한 다음 해결을 부탁해요.","an iced coffee, but this one is hot","a hot coffee, but this one is iced","뜨거운 커피를 주문했는데 아이스로 받은 상황으로 바꿔 말하세요."),
p("Could I have it without sugar? I'm trying to cut down on sweets.","설탕 없이 받을 수 있을까요? 단것을 줄이려고 하고 있어요.","Would you like anything added to your drink?","음료에 추가할 것이 있으세요?","설탕을 빼달라고 요청하고 단것을 줄이고 있다고 설명하세요.","without 뒤에 빼고 싶은 것을, cut down on 뒤에 줄이려는 것을 말해요.","without sugar","with less sugar","설탕을 완전히 빼는 대신 적게 넣어달라고 요청하세요."),
p("I'd like a table for two by the window. Is one available?","창가의 2인석을 원해요. 자리가 있나요?","Do you have a seating preference?","원하시는 자리가 있으세요?","창가의 2인석을 원한다고 말하고 가능한지 물어보세요.","인원수와 원하는 위치를 함께 말한 뒤 이용 가능 여부를 물어요.","for two","for three","인원수를 2명에서 3명으로 바꿔 말하세요."),
p("We only have thirty minutes for lunch. Which dishes can be served quickly?","점심 먹을 시간이 30분밖에 없어요. 빨리 나오는 메뉴는 무엇인가요?","Would you like a recommendation?","추천해 드릴까요?","점심 시간이 30분뿐이라고 밝히고 빨리 나오는 메뉴를 물어보세요.","시간 제약을 먼저 설명하면 상황에 맞는 추천을 받기 쉬워요.","thirty minutes","twenty minutes","식사할 수 있는 시간을 20분으로 바꿔 말하세요."),
p("Could we split the bill? We'd each like to pay for what we ordered.","따로 계산할 수 있을까요? 각자 주문한 것의 금액을 내고 싶어요.","How would you like to pay?","어떻게 계산하시겠어요?","계산서를 나누고 각자 주문한 금액을 내고 싶다고 구체적으로 말하세요.","split the bill만 말하면 똑같이 나누는 것으로 이해할 수 있어 원하는 방식을 덧붙여요.","pay for what we ordered","pay half of the total","각자 주문한 금액 대신 총액의 절반씩 내겠다고 말하세요.")
]},
{id:17,title:"마감이 어려울 때 협의하기",label:"직장 · 사유와 대안",scene:"마감까지 일을 끝내기 어려운 상황입니다. 막연한 사과에 그치지 말고 이유, 가능한 범위, 다음 시간을 제안해보세요.",phrases:[
p("I won't be able to finish the report today. Could I send it tomorrow morning instead?","오늘 보고서를 끝내기는 어려울 것 같아요. 대신 내일 아침에 보내도 될까요?","Will the report be ready today?","오늘 보고서가 준비되나요?","오늘 완료가 어렵다고 밝히고 내일 아침 제출을 제안하세요.","won't be able to는 할 수 없을 것이라는 뜻이에요. instead로 대안을 붙여요.","tomorrow morning","tomorrow afternoon","대안 제출 시간을 내일 오후로 바꿔 말하세요."),
p("I'm still waiting for the final figures. I'll finish the report as soon as I receive them.","최종 수치를 아직 기다리고 있어요. 받는 대로 보고서를 마무리할게요.","What's holding up the report?","보고서가 지연되는 이유가 뭔가요?","최종 수치를 기다린다고 설명하고 받는 즉시 마무리하겠다고 말하세요.","as soon as는 '~하자마자'예요. 뒤의 receive는 미래의 일이어도 현재형으로 써요.","final figures","updated prices","기다리는 자료를 최종 수치에서 수정된 가격으로 바꿔 말하세요."),
p("I can send you a draft by three. The final version will be ready tomorrow.","3시까지 초안을 보내드릴 수 있어요. 최종본은 내일 준비돼요.","Is there anything you can send me today?","오늘 보내줄 수 있는 자료가 있나요?","오늘 제공할 수 있는 초안의 시간과 최종본 일정을 나누어 말하세요.","draft와 final version을 구분하면 먼저 줄 수 있는 것과 나중에 줄 것을 분명히 할 수 있어요.","by three","by four","초안을 보낼 수 있는 시간을 4시까지로 바꿔 말하세요."),
p("Which task should I prioritize? I don't think I can finish both by noon.","어떤 업무를 먼저 해야 할까요? 정오까지 둘 다 끝내기는 어려울 것 같아요.","Can you finish the report and the quotation this morning?","오늘 오전에 보고서와 견적서를 끝낼 수 있나요?","두 일을 정오까지 끝내기 어렵다고 말하고 우선순위를 물어보세요.","prioritize는 우선 처리하다예요. I don't think ...로 판단을 조심스럽게 전해요.","by noon","by five","두 업무의 마감을 오후 5시까지로 바꿔 말하세요."),
p("I'm sorry for the delay. I've sent the revised file, and I'll double-check the schedule next time.","늦어져서 죄송해요. 수정 파일을 보냈고 다음에는 일정을 다시 확인할게요.","Have you resolved the issue?","문제는 해결했나요?","지연에 사과하고 완료한 조치와 다음번 개선 행동을 함께 설명하세요.","사과 뒤에 현재 조치와 다음 행동을 이어 말하면 상황을 더 명확히 전할 수 있어요.","the schedule","the deadline","다음에 다시 확인할 대상을 일정에서 마감 기한으로 바꿔 말하세요.")
]},
{id:18,title:"업무 진행 상황과 의견 말하기",label:"직장 · 보고와 제안",scene:"회의에서 진행 상황을 묻습니다. 끝난 일과 남은 일을 나누고, 판단에 이유를 붙여 말해보세요.",phrases:[
p("I've finished checking the documents. I'm now waiting for the customer's confirmation.","서류 확인은 끝냈어요. 지금은 고객의 확인을 기다리고 있어요.","How is the shipment preparation going?","선적 준비는 어떻게 진행되고 있나요?","완료한 서류 확인과 현재 기다리는 고객 확인을 구분해 말하세요.","I've finished 뒤에는 끝낸 일을, I'm now 뒤에는 현재 상황을 설명해요.","customer's confirmation","carrier's confirmation","고객 확인 대신 운송사의 확인을 기다린다고 말하세요."),
p("The first option is cheaper, but it takes two more days. I think the second option is better for this order.","첫 번째 방법은 저렴하지만 이틀 더 걸려요. 이 주문에는 두 번째 방법이 더 좋다고 생각해요.","Which option would you recommend?","어떤 방법을 추천하시겠어요?","첫 번째 방법의 비용과 시간 차이를 설명하고 두 번째 방법을 추천하세요.","비교한 뒤 I think로 판단을 덧붙여보세요. cheaper는 더 저렴한이라는 뜻이에요.","two more days","three more days","추가 소요 시간을 이틀에서 사흘로 바꿔 설명하세요."),
p("I agree with the plan, but I'm concerned about the cost. Could we compare a few more options?","계획에는 동의하지만 비용이 걱정돼요. 다른 방법도 몇 가지 비교해볼 수 있을까요?","What do you think of the plan?","이 계획에 대해 어떻게 생각하세요?","계획에 동의하면서 비용 우려를 밝히고 다른 선택지 비교를 제안하세요.","I'm concerned about으로 걱정되는 지점을 구체적으로 말할 수 있어요.","the cost","the delivery time","걱정되는 지점을 비용에서 배송 시간으로 바꿔 말하세요."),
p("From my experience, this route is more reliable. It may be worth paying a little extra.","제 경험으로는 이 경로가 더 안정적이에요. 비용을 조금 더 낼 만할 수도 있어요.","Why would you choose that route?","왜 그 경로를 선택하시겠어요?","경험상 더 안정적이라고 설명하고 추가 비용을 낼 가치가 있다고 제안하세요.","may be worth ...ing는 반드시 그렇다고 단정하지 않고 가치를 제안하는 표현이에요.","more reliable","faster","그 경로를 고르는 이유를 안정성에서 빠른 속도로 바꿔 말하세요."),
p("I'll contact the customer this afternoon. After that, I'll update the schedule and share it with the team.","오늘 오후에 고객에게 연락할게요. 그다음 일정을 수정해 팀에 공유할게요.","What are the next steps?","다음 단계는 무엇인가요?","고객 연락, 일정 수정, 팀 공유 순서로 다음 행동을 설명하세요.","After that으로 행동의 순서를 연결해보세요.","this afternoon","tomorrow morning","고객에게 연락할 시간을 내일 아침으로 바꿔 말하세요.")
]},
{id:19,title:"운송 지연과 확인 중인 내용 설명하기",label:"물류 · 고객 응대",scene:"연습용 화물의 운송 상태를 묻는 고객에게 답합니다. 확인된 사실과 아직 확인 중인 내용을 구분해서 말해보세요.",phrases:[
p("The vessel has been delayed because of bad weather. We're checking the revised arrival time.","기상 악화로 선박이 지연됐어요. 변경된 도착 시간을 확인하고 있어요.","Why hasn't the shipment arrived yet?","화물이 왜 아직 도착하지 않았나요?","기상으로 인한 선박 지연을 설명하고, 변경 도착 시간은 확인 중이라고 말하세요.","because of 뒤에는 bad weather처럼 명사를 써요. 확인 중인 사실은 checking으로 구분해요.","bad weather","port congestion","지연 사유를 기상 악화에서 항만 혼잡으로 바꿔 설명하세요."),
p("The current estimate is Thursday afternoon. I'll confirm it with the carrier before making any promises.","현재 예상은 목요일 오후예요. 확답을 드리기 전에 운송사에 확인할게요.","Can you guarantee delivery by Thursday?","목요일까지 배송을 보장할 수 있나요?","현재는 목요일 오후로 예상되지만 확답 전에 운송사 확인이 필요하다고 말하세요.","estimate는 예상이에요. 예상과 확정을 구분해 설명하는 연습을 해보세요.","Thursday afternoon","Friday morning","예상 도착 시점을 금요일 오전으로 바꿔 말하세요."),
p("We need the packing list to complete the paperwork. Could you send it by ten tomorrow?","서류 처리를 마치려면 패킹리스트가 필요해요. 내일 10시까지 보내주시겠어요?","Is there anything you still need from us?","저희가 더 보내드려야 하는 것이 있나요?","패킹리스트가 필요한 이유와 전달 마감을 함께 요청하세요.","need A to B는 B를 하기 위해 A가 필요하다는 뜻이에요.","packing list","commercial invoice","필요한 서류를 패킹리스트에서 상업송장으로 바꿔 요청하세요."),
p("We're checking another route to reduce the delay. I'll let you know if it changes the cost.","지연을 줄이기 위해 다른 경로를 확인하고 있어요. 비용이 바뀌면 알려드릴게요.","Is there another way to get it there sooner?","더 빨리 보낼 다른 방법이 있나요?","대체 경로를 확인 중이라고 말하고 비용 변동 여부도 알리겠다고 하세요.","to reduce the delay로 대체 경로를 찾는 목적을 설명해요.","the cost","the delivery date","추가로 안내할 내용을 비용 변동에서 배송일 변경으로 바꿔 말하세요."),
p("I understand this is urgent. I'll send you an update by three, even if we're still waiting for confirmation.","급한 건인 점 이해해요. 아직 확답을 기다리는 중이더라도 3시까지 진행 상황을 보내드릴게요.","Please keep us informed. Our production team is waiting.","계속 상황을 알려주세요. 생산팀에서 기다리고 있어요.","긴급성을 이해한다고 밝히고, 확답이 없어도 3시까지 중간 상황을 알리겠다고 하세요.","even if는 '설령 ~하더라도'예요. 진행 상황을 알릴 시점과 확정 시점을 구분하세요.","by three","by four","중간 상황을 알릴 시간을 4시까지로 바꿔 말하세요.")
]},
{id:20,title:"짧은 보고와 대화를 스스로 마무리하기",label:"종합 · 두세 문장 말하기",scene:"상황을 요약한 뒤 다음 행동이나 질문을 붙여봅니다. 예시를 외우기보다 자신의 일상과 업무에 맞게 바꾸어보세요.",phrases:[
p("The customer approved the quotation this morning. I'm preparing the documents now, and I expect to finish by four.","고객이 오늘 아침 견적을 승인했어요. 지금 서류를 준비하고 있고 4시까지 마칠 예정이에요.","Could you give us a quick update?","짧게 진행 상황을 알려주시겠어요?","고객 승인, 현재 하는 일, 예상 완료 시간을 차례로 보고하세요.","이미 일어난 일, 지금 하는 일, 다음 계획을 시제에 맞춰 구분해보세요.","by four","by five","예상 완료 시간을 5시까지로 바꿔 보고하세요."),
p("We agreed to move the meeting to Friday. I'll send the updated invitation, and Sam will prepare the figures.","회의를 금요일로 옮기기로 했어요. 제가 수정된 초대를 보내고 Sam은 수치를 준비할 거예요.","What did we decide in the meeting?","회의에서 무엇을 결정했나요?","변경된 회의일과 자신 및 Sam이 할 일을 정리해서 말하세요.","We agreed to로 합의한 내용을 말하고 각자의 역할을 이어 설명해요.","Friday","Thursday","변경된 회의일을 목요일로 바꿔 정리하세요."),
p("I've completed the urgent tasks, but I still need to review one file. Is there anything else you need before I leave?","급한 업무는 끝냈지만 파일 하나를 더 검토해야 해요. 퇴근 전에 더 필요한 것이 있나요?","Are you ready to leave for the day?","이제 퇴근할 준비가 됐나요?","완료한 일과 남은 일을 말하고 퇴근 전 추가 요청이 있는지 물어보세요.","완료와 미완료를 but으로 구분하고 마지막에 확인 질문을 붙여보세요.","review one file","reply to one email","남은 일을 파일 하나 검토에서 이메일 한 건 답장으로 바꿔 말하세요."),
p("I learned a useful way to ask for more time. Tomorrow, I want to practice explaining a problem clearly.","시간을 더 요청하는 유용한 표현을 배웠어요. 내일은 문제를 명확히 설명하는 연습을 하고 싶어요.","What did you learn today, and what would you like to practice next?","오늘 무엇을 배웠고, 다음에는 무엇을 연습하고 싶으세요?","오늘 배운 것과 내일 연습할 목표를 각각 말하세요.","학습한 내용도 두 문장으로 정리해보세요. explaining 뒤에는 설명할 대상을 붙여요.","a problem","a delay","다음에 설명할 대상을 일반적인 문제에서 지연으로 바꿔 말하세요."),
p("Let me summarize the next steps. I'll confirm the schedule, contact the customer, and send you an update by noon.","다음 단계를 정리할게요. 일정을 확인하고 고객에게 연락한 뒤 정오까지 진행 상황을 보내드릴게요.","Before we finish, can you confirm what you'll do next?","마치기 전에 다음에 할 일을 확인해 주시겠어요?","일정 확인, 고객 연락, 정오까지 상황 공유의 순서로 다음 행동을 요약하세요.","Let me summarize로 요약을 시작하고, 행동을 순서대로 연결하세요.","by noon","by three","진행 상황을 공유할 마감을 오후 3시까지로 바꿔 요약하세요.")
]}
];

export const workStages = [
{title:"맥락 듣기",sub:"질문과 답의 연결 이해하기",hint:"상대가 무엇을 원하는지 먼저 들어보세요. 답에서 이유·상황·다음 행동을 찾아보세요."},
{title:"답변 늘리기",sub:"대답에 이유와 질문 붙이기",hint:"쉬운 문장을 연결해 두세 문장으로 답해보세요. 표현을 통째로 외우기보다 연결 방식을 익혀보세요."},
{title:"따라 말하기",sub:"의미 단위로 묶어서 말하기",hint:"이유나 추가 질문 앞에서 잠깐 쉬어가며 따라 해보세요. 대답 전체를 자연스럽게 이어보는 연습이에요."},
{title:"직접 대답하기",sub:"선택지 없이 답변 만들기",hint:"상황에 맞게 두세 문장으로 답하세요. 조용한 곳에서는 입력으로 연습할 수 있어요. 다른 자연스러운 답도 가능해요."},
{title:"조건 바꿔 말하기",sub:"시간·이유·조건을 바꿔보기",hint:"새 조건에 맞춰 답변을 바꾸세요. 먼저 직접 써본 뒤 예시와 비교해보세요."},
{title:"도움 없이 복습",sub:"예시를 가리고 답 떠올리기",hint:"상대의 질문을 듣고 답을 만들어보세요. 예시를 본 뒤 필요한 내용을 전달했는지 직접 확인해보세요."}
];
